version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Milan9805"
  - package-ecosystem: "npm"
    directory: "/deployGenericSnsTopic/"
    schedule:
      interval: "daily"
    reviewers:
      - "Milan9805"
  - package-ecosystem: "npm"
    directory: "/setTopicAttributes/"
    schedule:
      interval: "daily"
    reviewers:
      - "Milan9805"
