#!/usr/bin/env bash

AWS_ACCOUNT_ID=$(grep AWS_ACCOUNT_ID .env | cut -d '=' -f 2-)
export $(egrep -v '^#' .env | xargs)

echo "Synthesizing CloudFormation template for AWS account: $AWS_ACCOUNT_ID"
npx cdk synth