name: cdk deploy

on:
  push:
    branches: [production]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
          - name: "checkout branch"
            uses: actions/checkout@v2
          - name: "setup node"
            uses: actions/setup-node@v1
            with:
                node-version: 12
                registry-url: "https://registry.npmjs.org/"
          - name: "get repo name as environment variable"
            uses: franzdiebold/github-env-vars-action@v1.0.0
          - name: "install set-topic-attributes lambda"
            run: |
                cd setTopicAttributes
                npm ci
          - name: "test set-topic-attributes lambda"
            run: |
                cd setTopicAttributes
                npm run test
          - name: "package set-topic-attributes lambda"
            run: |
                cd setTopicAttributes
                npm run package
          - name: "install generic sns topic stack"
            run: |
                cd deployGenericSnsTopic
                npm ci
          - name: "test generic sns topic stack"
            run: |
                cd deployGenericSnsTopic
                npm run test
          - name: "build generic sns topic stack"
            run: |
                cd deployGenericSnsTopic
                npm run build
          - name: "deploy generic sns topic stack"
            env:
              AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
              AWS_ACCOUNT_ID: "${{secrets.AWS_ACCOUNT_ID}}"
              AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
              AWS_DEFAULT_REGION: "eu-west-1"
              PUSHED_BY: "github"
            run: |
              cd deployGenericSnsTopic
              npx cdk bootstrap \
              --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/CloudformationDeploymentRole \
              --toolkit-stack-name $GITHUB_REPOSITORY_NAME-generic-sns-topic-cdk-toolkit
              npx cdk deploy \
              --require-approval never \
              --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/CloudformationDeploymentRole \
              --toolkit-stack-name $GITHUB_REPOSITORY_NAME-generic-sns-topic-cdk-toolkit
          - name: Invoke set-topic-attributes Lambda
            uses: gagoar/invoke-aws-lambda@master
            with:
              AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_INVOKE_TOPIC_LAMBDA_USER}}
              AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_INVOKE_TOPIC_LAMBDA_USER}}
              REGION: "eu-west-1"
              FunctionName: set-topic-attributes
              Payload: '{
                          "http": {
                            "defaultHealthyRetryPolicy": {
                              "minDelayTarget": 5,
                              "maxDelayTarget": 1200,
                              "numRetries": 5,
                              "numMaxDelayRetries": 1,
                              "numNoDelayRetries": 1,
                              "backoffFunction": "exponential"
                            },
                            "disableSubscriptionOverrides": false
                          }
                        }'
