name: "Automatically merge dependabot PRs"
on:
  schedule:
  - cron: "0 0 10 ? * * *"

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: merge
        run: bash mergeBumps.sh
        