name: Tests

on: push

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: "Install root project"
        run: npm install
      - name: "Test project"
        run: npm run test